apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: server-container
          image: server-client
          imagePullPolicy: Never
          ports:
          - containerPort: 1234