apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/component: frontend
spec:
  ports:
    - port: 1234
      targetPort: 1234
  selector:
      app.kubernetes.io/name: server
      app.kubernetes.io/component: frontend


